version: "3.8"

services:
  # Сервис Web API
  web_api:
    build: .
    container_name: web_api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=mylabdb
      - DB_USER=postgres
      - DB_PASS=mysecretpassword

  # PostgreSQL
  postgres:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mylabdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  # Kafka Broker
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_CREATE_TOPICS=user_events:10:3
    ports:
      - "9092:9092"
      - "9093:9093"
    depends_on:
      - zookeeper

  # Spark Streaming
  sspark:
    image: bitnami/spark:latest
    container_name: spark_streaming
    volumes:
      - ./data:/app/data
      - ./:/app
    working_dir: /app
    command: >
      spark-submit --master local[2] --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.5 spark_streaming.py
    depends_on:
      - kafka

  # Kafka Consumer для Cassandra
  kafka_consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    container_name: kafka_consumer
    depends_on:
      - kafka
      - cassandra
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - KAFKA_TOPIC=user_events
      - CASSANDRA_HOST=cassandra_db
      - CASSANDRA_PORT=9042
      - KEYSPACE=mykeyspace
      - TABLE=user_events
    restart: "no"

  # Apache Cassandra
  cassandra:
    image: cassandra:3.11
    container_name: cassandra_db
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  pgdata:
  cassandra_data: